spring.application.name=Employee_Management_System_By_Using_Spring_REST_API

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

# Root logging level (adjust as needed)
logging.level.root = INFO

# Base log file name and location
logging.file.name=logs/demofile.log

# Rolling file configuration
logging.logback.rollingpolicy.file-name-pattern=logs/demofile.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=7
#logging.logback.rollingpolicy.clean-history-on-start=true